name: Python tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    # 모든 스텝의 기본 작업 디렉토리를 'api'로 설정합니다.
    defaults:
      run:
        working-directory: ./api
        
    env:
      DB_USER: "test_user"
      DB_PASSWORD: "test_password"
      DB_NAME: "test_db"
      REDIS_PASSWORD: "test_password"
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install uv
          # '--with test' 옵션을 추가하여 pytest를 포함한 테스트 의존성을 설치합니다.
          uv sync --with test

      - name: Run tests
        run: |
          # working-directory 설정으로 인해 이미 'api' 디렉토리 내에서 실행됩니다.
          uv run python -m pytest -vv tests/